projects:
  ygh:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default:
          url: "https://api.yourgifthunt.com/prisma/hunt-api/dev"
          headers:
            Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJncmFudHMiOlt7InRhcmdldCI6IiovKiIsImFjdGlvbiI6IioifV0sImlhdCI6MTU1ODY0MTAyMiwiZXhwIjoxODc0MDAxMDIyfQ.kpIOCymaoZEWecjF3RnHSebtfUWRxAS4_-aAzT2TvCE"
