[build]
  command = "yarn build"
  publish = "build"
  functions = "src/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "yarn start"
  publish = "build"
  functions = "src/functions"
